// Mock species data based on CSV + additional fields for filters
export const mockSpeciesData = [
  {
    id: 1,
    scientificName: "Thunnus albacares",
    vernacularName: "Yellowfin tuna",
    kingdom: "Animalia",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Scombridae",
    genus: "Thunnus",
    species: "albacares",
    maxLengthCm: 250,
    avgLengthCm: 150,
    maxWeightKg: 200,
    avgWeightKg: 100,
    bodyShape: "fusiform",
    colorPattern: "dark metallic blue back with yellow fins",
    ageOfMaturityYears: 2,
    habitatType: "pelagic",
    depthRangeMin: 0,
    depthRangeMax: 500,
    temperatureRangeMin: 18,
    temperatureRangeMax: 30,
    salinityRangeMin: 33,
    salinityRangeMax: 37,
    diet: "small fish, squid, crustaceans",
    trophicLevel: 4.3,
    migrationPatterns: "long-distance",
    reportedRegions: [
      "Arabian Sea",
      "Bay of Bengal",
      "Indian Ocean",
      "Lakshadweep",
      "Goa",
      "Kerala",
      "Karnataka",
      "Maharashtra",
      "Gujarat",
    ],
    iucnStatus: "Least Concern",
    populationTrend: "stable",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400",
    imageUrls: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400",
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400",
    ],
    lastSightingDate: new Date("2024-11-20"),
    lastSightingLocation: "Bay of Bengal",
    lastSightingDepth: 45,
    dataQuality: "Verified Species", // Verified Species | AI-Analyzed Records | eDNA Confirmed
    description:
      "The yellowfin tuna is one of the largest, fastest, and most gorgeously colored of all the world's fishes. Found in tropical and subtropical seas, it is an important species for commercial fishing.",
    maxAge: 35,
    totalBiomass: "850 Tons",
    cpue: "14.2 kg/hook",
    recruitment: "Moderate (Year Class 2023)",
  },
  {
    id: 2,
    scientificName: "Thunnus obesus",
    vernacularName: "Bigeye tuna",
    kingdom: "Animalia",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Scombridae",
    genus: "Thunnus",
    species: "obesus",
    maxLengthCm: 250,
    avgLengthCm: 180,
    maxWeightKg: 210,
    avgWeightKg: 150,
    bodyShape: "fusiform",
    colorPattern: "dark blue back, silver belly",
    ageOfMaturityYears: 3,
    habitatType: "pelagic",
    depthRangeMin: 0,
    depthRangeMax: 600,
    temperatureRangeMin: 16,
    temperatureRangeMax: 28,
    salinityRangeMin: 33,
    salinityRangeMax: 37,
    diet: "fish, squid, crustaceans",
    trophicLevel: 4.4,
    migrationPatterns: "long-distance",
    reportedRegions: [
      "Arabian Sea",
      "Bay of Bengal",
      "Indian Ocean",
      "Andaman and Nicobar",
      "Lakshadweep",
    ],
    iucnStatus: "Vulnerable",
    populationTrend: "decreasing",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1560275619-4662e36fa65c?w=400",
    imageUrls: [
      "https://images.unsplash.com/photo-1560275619-4662e36fa65c?w=400",
    ],
    lastSightingDate: new Date("2024-11-18"),
    lastSightingLocation: "Indian Ocean",
    lastSightingDepth: 350,
    dataQuality: "AI-Analyzed Records",
    description:
      "Bigeye tuna are large predatory fish found in deep tropical waters of the Atlantic, Pacific and Indian Oceans.",
    maxAge: 32,
    totalBiomass: "650 Tons",
    cpue: "12.1 kg/hook",
    recruitment: "Low (Year Class 2023)",
  },
  {
    id: 3,
    scientificName: "Katsuwonus pelamis",
    vernacularName: "Skipjack tuna",
    kingdom: "Animalia",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Scombridae",
    genus: "Katsuwonus",
    species: "pelamis",
    maxLengthCm: 110,
    avgLengthCm: 80,
    maxWeightKg: 34,
    avgWeightKg: 20,
    bodyShape: "fusiform",
    colorPattern: "dark back with 4–6 stripes",
    ageOfMaturityYears: 1.5,
    habitatType: "pelagic",
    depthRangeMin: 0,
    depthRangeMax: 300,
    temperatureRangeMin: 20,
    temperatureRangeMax: 31,
    salinityRangeMin: 33,
    salinityRangeMax: 37,
    diet: "fish, squid, zooplankton",
    trophicLevel: 4.0,
    migrationPatterns: "long-distance",
    reportedRegions: [
      "Arabian Sea",
      "Bay of Bengal",
      "Indian Ocean",
      "Goa",
      "Kerala",
      "Karnataka",
      "Maharashtra",
      "Gujarat",
      "Tamil Nadu",
      "Andhra Pradesh",
    ],
    iucnStatus: "Least Concern",
    populationTrend: "stable",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1520990894801-df1493ada628?w=400",
    imageUrls: [
      "https://images.unsplash.com/photo-1520990894801-df1493ada628?w=400",
    ],
    lastSightingDate: new Date("2024-11-22"),
    lastSightingLocation: "Arabian Sea",
    lastSightingDepth: 120,
    dataQuality: "eDNA Confirmed",
    description:
      "Skipjack tuna are small pelagic fish found in tropical oceans worldwide. They are highly migratory and form large schools.",
    maxAge: 16,
    totalBiomass: "1200 Tons",
    cpue: "18.5 kg/hook",
    recruitment: "High (Year Class 2023)",
  },
  {
    id: 4,
    scientificName: "Euthynnus affinis",
    vernacularName: "Kawakawa",
    kingdom: "Animalia",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Scombridae",
    genus: "Euthynnus",
    species: "affinis",
    maxLengthCm: 100,
    avgLengthCm: 65,
    maxWeightKg: 12,
    avgWeightKg: 8,
    bodyShape: "fusiform",
    colorPattern: "spotted back pattern",
    ageOfMaturityYears: 1.5,
    habitatType: "pelagic",
    depthRangeMin: 0,
    depthRangeMax: 250,
    temperatureRangeMin: 20,
    temperatureRangeMax: 31,
    salinityRangeMin: 33,
    salinityRangeMax: 37,
    diet: "fish, prawns, cephalopods",
    trophicLevel: 3.9,
    migrationPatterns: "seasonal",
    reportedRegions: [
      "Arabian Sea",
      "Bay of Bengal",
      "Indian Ocean",
      "Lakshadweep",
      "Goa",
      "Kerala",
      "Karnataka",
      "Maharashtra",
    ],
    iucnStatus: "Least Concern",
    populationTrend: "stable",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400",
    imageUrls: [
      "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400",
    ],
    lastSightingDate: new Date("2024-11-21"),
    lastSightingLocation: "Goa coast",
    lastSightingDepth: 80,
    dataQuality: "Verified Species",
    description:
      "Kawakawa are small tuna found throughout the Indo-Pacific region. They are important in subsistence and artisanal fisheries.",
    maxAge: 12,
    totalBiomass: "450 Tons",
    cpue: "9.3 kg/hook",
    recruitment: "Moderate (Year Class 2023)",
  },
  {
    id: 5,
    scientificName: "Auxis thazard",
    vernacularName: "Frigate tuna",
    kingdom: "Animalia",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Scombridae",
    genus: "Auxis",
    species: "thazard",
    maxLengthCm: 60,
    avgLengthCm: 45,
    maxWeightKg: 3,
    avgWeightKg: 2,
    bodyShape: "fusiform",
    colorPattern: "dark back with horizontal stripes",
    ageOfMaturityYears: 1,
    habitatType: "pelagic",
    depthRangeMin: 0,
    depthRangeMax: 200,
    temperatureRangeMin: 20,
    temperatureRangeMax: 30,
    salinityRangeMin: 33,
    salinityRangeMax: 37,
    diet: "small fish, squid",
    trophicLevel: 4.0,
    migrationPatterns: "seasonal",
    reportedRegions: [
      "Arabian Sea",
      "Bay of Bengal",
      "Indian Ocean",
      "Lakshadweep",
      "Kerala",
      "Karnataka",
    ],
    iucnStatus: "Least Concern",
    populationTrend: "stable",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400",
    imageUrls: [
      "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=400",
    ],
    lastSightingDate: new Date("2024-11-19"),
    lastSightingLocation: "Lakshadweep",
    lastSightingDepth: 150,
    dataQuality: "AI-Analyzed Records",
    description:
      "Frigate tuna are small mackerels found in Indo-Pacific waters. They form schools and are preyed upon by larger predatory fish.",
    maxAge: 8,
    totalBiomass: "200 Tons",
    cpue: "6.2 kg/hook",
    recruitment: "High (Year Class 2023)",
  },
  {
    id: 6,
    scientificName: "Sarda orientalis",
    vernacularName: "Striped bonito",
    kingdom: "Animalia",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Scombridae",
    genus: "Sarda",
    species: "orientalis",
    maxLengthCm: 75,
    avgLengthCm: 55,
    maxWeightKg: 5,
    avgWeightKg: 3,
    bodyShape: "fusiform",
    colorPattern: "strong dark stripes across back",
    ageOfMaturityYears: 2,
    habitatType: "pelagic",
    depthRangeMin: 0,
    depthRangeMax: 200,
    temperatureRangeMin: 18,
    temperatureRangeMax: 30,
    salinityRangeMin: 33,
    salinityRangeMax: 37,
    diet: "squid, small fish",
    trophicLevel: 3.8,
    migrationPatterns: "seasonal",
    reportedRegions: [
      "Arabian Sea",
      "Bay of Bengal",
      "Indian Ocean",
      "Andaman and Nicobar",
      "Lakshadweep",
    ],
    iucnStatus: "Least Concern",
    populationTrend: "stable",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1520990894801-df1493ada628?w=400",
    imageUrls: [
      "https://images.unsplash.com/photo-1520990894801-df1493ada628?w=400",
    ],
    lastSightingDate: new Date("2024-11-20"),
    lastSightingLocation: "Arabian Sea",
    lastSightingDepth: 100,
    dataQuality: "eDNA Confirmed",
    description:
      "Striped bonito are small predatory fish found in Indo-Pacific waters. They are important in local fisheries.",
    maxAge: 10,
    totalBiomass: "300 Tons",
    cpue: "7.8 kg/hook",
    recruitment: "Moderate (Year Class 2023)",
  },
  {
    id: 7,
    scientificName: "Scomberomorus commerson",
    vernacularName: "King seerfish",
    kingdom: "Animalia",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Scombridae",
    genus: "Scomberomorus",
    species: "commerson",
    maxLengthCm: 240,
    avgLengthCm: 150,
    maxWeightKg: 45,
    avgWeightKg: 30,
    bodyShape: "fusiform",
    colorPattern: "silver body with broken bars",
    ageOfMaturityYears: 2,
    habitatType: "pelagic/nearshore",
    depthRangeMin: 0,
    depthRangeMax: 150,
    temperatureRangeMin: 22,
    temperatureRangeMax: 30,
    salinityRangeMin: 33,
    salinityRangeMax: 37,
    diet: "fish, prawns",
    trophicLevel: 4.2,
    migrationPatterns: "long-distance",
    reportedRegions: [
      "Arabian Sea",
      "Bay of Bengal",
      "Indian Ocean",
      "Lakshadweep",
      "Goa",
      "Kerala",
      "Karnataka",
      "Maharashtra",
      "Gujarat",
      "Andhra Pradesh",
    ],
    iucnStatus: "Near Threatened",
    populationTrend: "decreasing",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400",
    imageUrls: [
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=400",
    ],
    lastSightingDate: new Date("2024-11-17"),
    lastSightingLocation: "Kerala coast",
    lastSightingDepth: 90,
    dataQuality: "Verified Species",
    description:
      "King seerfish are large, fast-swimming predators found in Indian Ocean and Indo-Pacific waters. They are highly valued in commercial fisheries.",
    maxAge: 28,
    totalBiomass: "520 Tons",
    cpue: "11.5 kg/hook",
    recruitment: "Low (Year Class 2023)",
  },
  {
    id: 8,
    scientificName: "Scomberomorus guttatus",
    vernacularName: "Indo-Pacific seerfish",
    kingdom: "Animalia",
    phylum: "Chordata",
    class: "Actinopterygii",
    order: "Perciformes",
    family: "Scombridae",
    genus: "Scomberomorus",
    species: "guttatus",
    maxLengthCm: 100,
    avgLengthCm: 70,
    maxWeightKg: 10,
    avgWeightKg: 6,
    bodyShape: "fusiform",
    colorPattern: "silver body with faint spots",
    ageOfMaturityYears: 1.5,
    habitatType: "pelagic/nearshore",
    depthRangeMin: 0,
    depthRangeMax: 120,
    temperatureRangeMin: 22,
    temperatureRangeMax: 30,
    salinityRangeMin: 33,
    salinityRangeMax: 37,
    diet: "small fish, crustaceans",
    trophicLevel: 4.0,
    migrationPatterns: "seasonal",
    reportedRegions: [
      "Arabian Sea",
      "Bay of Bengal",
      "Indian Ocean",
      "Lakshadweep",
      "Goa",
      "Kerala",
      "Karnataka",
      "Maharashtra",
      "Gujarat",
    ],
    iucnStatus: "Least Concern",
    populationTrend: "stable",
    thumbnailUrl:
      "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400",
    imageUrls: [
      "https://images.unsplash.com/photo-1583212292454-1fe6229603b7?w=400",
    ],
    lastSightingDate: new Date("2024-11-23"),
    lastSightingLocation: "Bay of Bengal",
    lastSightingDepth: 70,
    dataQuality: "AI-Analyzed Records",
    description:
      "Indo-Pacific seerfish are smaller relatives of king seerfish, found in Indo-West Pacific waters. They are important in coastal fisheries.",
    maxAge: 15,
    totalBiomass: "380 Tons",
    cpue: "8.7 kg/hook",
    recruitment: "Moderate (Year Class 2023)",
  },
];

export const conservationStatuses = [
  "Least Concern",
  "Vulnerable",
  "Endangered",
  "Critically Endangered",
  "Near Threatened",
];
export const dataQualities = [
  "Verified Species",
  "AI-Analyzed Records",
  "eDNA Confirmed",
];
export const classes = [
  "Actinopterygii",
  "Elasmobranchii",
  "Cephalaspidomorphi",
];
